<?php

/**
 * @version $Id$
 * @author Rene Kanzler <rk (at) cosmomill (dot) de>
 */
 
$labels = array();
$labels['opendocument'] = 'Dokument ansehen';
$labels['unsupporteddoctype'] = 'Dokumentformat wird nicht unterstützt.';
$labels['imageuploadfailed'] = 'Fehler beim upload des Bildes.';
$labels['zohosaveurl'] = 'Öffentliche URL zum speichen der Dokumente';
$labels['pixlrsaveurl'] = 'Öffentliche URL zum speichen der Bilder';
$labels['accesskey'] = 'Zugriffsschlüssel des Dokumentenserver';
$labels['enableeditor'] = 'Editor Modus aktivieren';
$labels['pagenrof'] = 'von';

?>
