<?php

$labels = [];
$labels['cloud_view_document'] = 'Cloud View';

// settings page
$labels['plugin_settings_title'] = 'Cloud View';
$labels['plugin_enabled'] = 'Plugin aktivieren';
$labels['select_viewer'] = 'Bevorzugter Cloud viewer';
$labels['viewers_tried_from_top_to_buttom'] = 'Viewer werden von oben nach unten probiert. Sie können mittels Drag and Drop der nachfolgenden Elemente die Reihenfolge anpassen.';
$labels['viewer_google_docs'] = 'Google Docs';
$labels['viewer_microsoft_office_web'] = 'Microsoft Office Web';
$labels['viewer_pdf_js'] = 'PDF (JS)';
$labels['viewer_markdown_js'] = 'Markdown (JS)';
$labels['viewer_stack_edit'] = 'StackEdit';
$labels['viewer_psd_js'] = 'PSD (JS)';
$labels['viewer_html_js'] = 'HTML (JS)';
$labels['select_view_button_layouts'] = 'Layout der Buttons für die bevorzugte Viewer';
$labels['view_button_layout_in_attachmentslist'] = 'In der Auflistung der Anhänge';
$labels['view_button_layout_in_attachmentoptionsmenu'] = 'In dem Optionsmenü für die Anhänge';