<?php

$labels = [];
$labels['cloud_view_document'] = 'Cloud View';

// settings page
$labels['plugin_settings_title'] = 'Cloud View';
$labels['plugin_enabled'] = 'Enable plugin';
$labels['select_viewer'] = 'Preferred cloud viewer';
$labels['viewer_google_docs'] = 'Google Docs';
$labels['viewer_microsoft_office_web'] = 'Microsoft Office Web';
$labels['select_view_button_layouts'] = 'Preferred view button layouts';
$labels['view_button_layout_in_attachmentslist'] = 'In the attachments list';
$labels['view_button_layout_in_attachmentoptionsmenu'] = 'In the attachment option menu';
