<?php
/**
 * @version $Id$
 * @author Rene Kanzler <rk (at) cosmomill (dot) de>
 */
 
$labels = array();
$labels['opendocument'] = 'View document';
$labels['unsupporteddoctype'] = 'Document type not supported';
$labels['imageuploadfailed'] = 'Image upload failed';
$labels['zohosaveurl'] = 'Publicly accessible URL to store documents';
$labels['pixlrsaveurl'] = 'Publicly accessible URL to store images';
$labels['accesskey'] = 'Document store access key';
$labels['enableeditor'] = 'Enable edit mode';

?>