<?php

$labels = [];
$labels['cloud_view_document'] = 'Cloud View';

// settings page
$labels['plugin_settings_title'] = 'Cloud View';
$labels['plugin_enabled'] = 'Enable plugin';
$labels['select_viewer'] = 'Preferred cloud viewer';
$labels['viewers_tried_from_top_to_buttom'] = 'Viewers will be tried from the top one to the bottom one. You can drag and drop following list items to change the order.';
$labels['viewer_google_docs'] = 'Google Docs';
$labels['viewer_microsoft_office_web'] = 'Microsoft Office Web';
$labels['viewer_pdf_js'] = 'PDF (JS)';
$labels['viewer_markdown_js'] = 'Markdown (JS)';
$labels['select_view_button_layouts'] = 'Preferred view button layouts';
$labels['view_button_layout_in_attachmentslist'] = 'In the attachments list';
$labels['view_button_layout_in_attachmentoptionsmenu'] = 'In the attachment option menu';
