<?php

$labels = [];
$labels['cloud_view_document'] = 'Cloud View';

// settings page
$labels['plugin_settings_title'] = 'Cloud View';
$labels['plugin_enabled'] = 'Aktiver plugin';
$labels['select_viewer'] = 'Foretrukket cloud viewer';
$labels['viewers_tried_from_top_to_buttom'] = 'Visning i prioritets rekkefølge. Klikk og dra for å endre rekkefølge.';
$labels['viewer_google_docs'] = 'Google Docs';
$labels['viewer_microsoft_office_web'] = 'Microsoft Office Web';
$labels['viewer_pdf_js'] = 'PDF (JS)';
$labels['viewer_markdown_js'] = 'Markdown (JS)';
$labels['viewer_stack_edit'] = 'StackEdit';
$labels['viewer_psd_js'] = 'PSD (JS)';
$labels['viewer_html_js'] = 'HTML (JS)';
$labels['select_view_button_layouts'] = 'Foretrukket view button layouts';
$labels['view_button_layout_in_attachmentslist'] = 'Listen over vedlegg';
$labels['view_button_layout_in_attachmentoptionsmenu'] = 'Menyen for vedleggsinnstillinger';
