<?php

// Por Marcelo Leães
// marcelo@eth1.com.br

$labels = [];
$labels['cloud_view_document'] = 'Cloud Viewer';
$labels['plugin_settings_title'] = 'Cloud Viewer';
$labels['plugin_enabled'] = 'Habilitar';
$labels['select_viewer'] = 'Visualizador padrão';
$labels['viewers_tried_from_top_to_buttom'] = 'O visualizador padrão será sempre o do topo nesta lista.';
$labels['viewer_google_docs'] = 'Google Docs';
$labels['viewer_microsoft_office_web'] = 'Microsoft Office Web';
$labels['viewer_pdf_js'] = 'PDF (JS)';
$labels['viewer_markdown_js'] = 'Markdown (JS)';
$labels['viewer_stack_edit'] = 'StackEdit';
$labels['viewer_psd_js'] = 'PSD (JS)';
$labels['viewer_html_js'] = 'HTML (JS)';
$labels['select_view_button_layouts'] = 'Preferências de layout';
$labels['view_button_layout_in_attachmentslist'] = 'Mostrar ao lado dos anexos';
$labels['view_button_layout_in_attachmentoptionsmenu'] = 'Mostrar no menu de anexos';
