<?php

$labels = [];
$labels['cloud_view_document'] = 'Просмотреть';

// страница настроек
$labels['plugin_settings_title'] = 'Cloud View';
$labels['plugin_enabled'] = 'Включить Cloud View';
$labels['select_viewer'] = 'Предпочитаемый сервис просмотра';
$labels['viewer_google_docs'] = 'Google Docs';
$labels['viewer_microsoft_office_web'] = 'Microsoft Office Web';
$labels['viewer_pdf_js'] = 'PDF (JS)';
$labels['viewer_markdown_js'] = 'Markdown (JS)';
$labels['viewer_stack_edit'] = 'StackEdit';
$labels['viewer_psd_js'] = 'PSD (JS)';
