<?php

$labels = [];
$labels['cloud_view_document'] = 'Cloud View';

// settings page
$labels['plugin_settings_title'] = 'Cloud View';
$labels['plugin_enabled'] = 'Ввімкнути Cloud View';
$labels['select_viewer'] = 'Волітимий сервіс перегляду';
$labels['viewers_tried_from_top_to_buttom'] = 'Порядок застосування сервисів перегляду з верху до низу. Ви маєте змогу перетягувати елементи переліку, для зміни пріорітету.';
$labels['viewer_google_docs'] = 'Google Docs';
$labels['viewer_microsoft_office_web'] = 'Microsoft Office Web';
$labels['viewer_pdf_js'] = 'PDF (JS)';
$labels['viewer_markdown_js'] = 'Markdown (JS)';
$labels['viewer_stack_edit'] = 'StackEdit';
$labels['viewer_psd_js'] = 'PSD (JS)';
$labels['viewer_html_js'] = 'HTML (JS)';
$labels['select_view_button_layouts'] = 'Волітимий вигляд кнопки Cloud View';
$labels['view_button_layout_in_attachmentslist'] = 'У переліку вкладеннь';
$labels['view_button_layout_in_attachmentoptionsmenu'] = 'У контекстному меню вкладеннь';
