<?php

$labels = [];
$labels['cloud_view_document'] = '云浏览';

// settings page
$labels['plugin_settings_title'] = '云文件浏览器';
$labels['plugin_enabled'] = '启用插件';
$labels['select_viewer'] = '偏好的云文件浏览器';
$labels['viewer_google_docs'] = 'Google Docs';
$labels['viewer_microsoft_office_web'] = 'Microsoft Office Web';
$labels['select_view_button_layouts'] = '偏好的「浏览」按钮的显示方式';
$labels['view_button_layout_in_attachmentslist'] = '在附件清单中';
$labels['view_button_layout_in_attachmentoptionsmenu'] = '在附件的弹出式菜单中';
