<?php

$labels = [];
$labels['cloud_view_document'] = '雲端檢視';

// settings page
$labels['plugin_settings_title'] = '雲端檔案檢視器';
$labels['plugin_enabled'] = '啟用外掛';
$labels['select_viewer'] = '偏好的雲端檔案檢視器';
$labels['viewers_tried_from_top_to_buttom'] = '檢視器將會以由上到下的順序進行嘗試。你可以拖動他們來進行排序。';
$labels['viewer_google_docs'] = 'Google Docs';
$labels['viewer_microsoft_office_web'] = 'Microsoft Office Web';
$labels['viewer_pdf_js'] = 'PDF (JS)';
$labels['viewer_markdown_js'] = 'Markdown (JS)';
$labels['viewer_stack_edit'] = 'StackEdit';
$labels['viewer_psd_js'] = 'PSD (JS)';
$labels['viewer_html_js'] = 'HTML (JS)';
$labels['select_view_button_layouts'] = '偏好的「檢視」按鈕的顯示方式';
$labels['view_button_layout_in_attachmentslist'] = '在附件清單中';
$labels['view_button_layout_in_attachmentoptionsmenu'] = '在附件的彈出式選單中';
