<?php

$labels = [];
$labels['cloud_view_document'] = '雲端瀏覽';

// settings page
$labels['plugin_settings_title'] = '雲端文件瀏覽器';
$labels['plugin_enabled'] = '啟用外掛';
$labels['select_viewer'] = '偏好的雲端文件瀏覽器';
$labels['viewer_google_docs'] = 'Google Docs';
$labels['viewer_microsoft_office_web'] = 'Microsoft Office Web';
$labels['select_view_button_layouts'] = '偏好的「瀏覽」按鈕的顯示方式';
$labels['view_button_layout_in_attachmentslist'] = '在附件清單中';
$labels['view_button_layout_in_attachmentoptionsmenu'] = '在附件的彈出式選單中';
