import json
import re

# ext to mime types
mimeMap = {
    # "7z": ["application/x-7z-compressed"],
    # ...
}


def sortDictByKey(dct: dict) -> dict:
    """
    @brief Sort the dict by its key as of Python 3.7.

    @param dct The dict

    @return The sorted dict
    """

    dctNew = {}

    for key in sorted(dct.keys()):
        dctNew[key] = dct[key]

    return dctNew


with open("mime.types", "r", encoding="utf-8") as fp:
    for line in fp.readlines():
        parts = re.split(r"\s+", line.strip())

        if line.startswith("#") or len(parts) < 2:
            continue

        mimeType = parts[0]
        exts = parts[1:]

        for ext in exts:
            mimeMap.setdefault(ext, [])
            mimeMap[ext].append(mimeType)

    mimeMap = sortDictByKey(mimeMap)

# dump as json file
with open("mime.types.json", "w", encoding="utf-8", newline="\n") as fp:
    json.dump(mimeMap, fp, indent=2)

# dump as php file
with open("mime.types.php", "w", encoding="utf-8", newline="\n") as fp:
    indent = "    "

    out = "<?php\n\n// this file is auto-generated by a script\n\nreturn [\n"

    for ext, mimeTypes in mimeMap.items():
        mimes = ", ".join(map(lambda s: f"'{s}'", mimeTypes))
        out += f"{indent}'{ext}' => [{mimes}],\n"

    out += "];\n"

    fp.write(out)
